version: "3.9"

services:
  rag_api:
    build: .
    container_name: docchat_rag
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
    restart: unless-stopped
